const sanitize = url => url && (~url.indexOf('youtube') ? url.split('&')[0] : url.split('?')[0]);
const isSameDomain = (url1, url2) => url1.split('/')[2] === url2.split('/')[2];
const generateId = () => {
  var text = '';
  var possible = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';

  for (var i = 0; i < 8; i++)
    text += possible.charAt(Math.floor(Math.random() * possible.length));

  return text;
};
const getId = url => {
  const sanitizedUrl = sanitize(url);
  return Object.keys(webData).find(key => webData[key].url === sanitizedUrl);
};
const shuffle = a => {
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
};

const webData = {
  [generateId()]: {
    'favicon': 'https://github.githubassets.com/favicon.ico',
    'url': 'https://github.com/',
    'title': 'GitHub',
    'description': 'GitHub is where people build software. More than 31 million people use GitHub to discover, fork, and contribute to over 100 million projects.',
  },
  [generateId()]: {
    'url': 'https://github.com/algorithm-visualizer/algorithm-visualizer/issues/237',
    'favicon': 'https://github.githubassets.com/favicon.ico',
    'title': 'Advice on suitability for HMM algorithms · Issue #237 · algorithm-visualizer/algorithm-visualizer',
    'description': 'Do you think it would be very doable to develop a visualization of the Viterbi algorithm under the provided API? https://www.youtube.com/watch?v=0dVUfYF8ko0',
  },
  [[generateId()]]: {
    'url': 'https://github.com/algorithm-visualizer/algorithm-visualizer',
    'title': 'algorithm-visualizer/algorithm-visualizer: Interactive Online Platform that Visualizes Algorithms from Code',
    'favicon': 'https://github.githubassets.com/favicon.ico',
    'description': ':fireworks:Interactive Online Platform that Visualizes Algorithms from Code - algorithm-visualizer/algorithm-visualizer',
  },
  [[generateId()]]: {
    'url': 'https://github.com/algorithm-visualizer/tracers.js',
    'title': 'algorithm-visualizer/tracers.js: Visualization Library for JavaScript',
    'favicon': 'https://github.githubassets.com/favicon.ico',
    'description': 'Visualization Library for JavaScript. Contribute to algorithm-visualizer/tracers.js development by creating an account on GitHub.',
  },
  [[generateId()]]: {
    'url': 'https://github.com/parkjs814/gt-schedule-crawler',
    'title': 'parkjs814/gt-schedule-crawler',
    'favicon': 'https://github.githubassets.com/favicon.ico',
    'description': 'Contribute to parkjs814/gt-schedule-crawler development by creating an account on GitHub.',
  },
  [[generateId()]]: {
    'url': 'https://github.com/parkjs814/gt-scheduler',
    'title': 'parkjs814/gt-scheduler: GT Scheduler',
    'favicon': 'https://github.githubassets.com/favicon.ico',
    'description': ':calendar: GT Scheduler. Contribute to parkjs814/gt-scheduler development by creating an account on GitHub.',
  },
  [[generateId()]]: {
    'url': 'https://github.com/Homebrew/brew',
    'title': 'Homebrew/brew: 🍺 The missing package manager for macOS (or Linux)',
    'favicon': 'https://github.githubassets.com/favicon.ico',
    'description': '🍺 The missing package manager for macOS (or Linux) - Homebrew/brew',
  },
  [[generateId()]]: {
    'favicon': 'https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png',
    'title': 'Charlie Brown - YouTube',
    'url': 'https://www.youtube.com/watch?v=JZwU974Qdf4',
    'description': 'Provided to YouTube by Warner Music Group\n\nCharlie Brown · Coldplay\n\nMylo Xyloto\n\n℗ 2011 Parlophone Records Ltd, a Warner Music Group Company\n\nAssistant: Andy Rugg\nMastering  Engineer: Bob Ludwig\nMasterer: Bob Ludwig\nVocals: Brian Eno\nVocals: Chris Martin\nAssistant: Christian Green\nProducer: Daniel Green\nMixer: Dave Emery\nStrings: Davide Rossi\nStrings: Davide Rossi\nBass: Guy Berryman\nAssistant: Ian Shea\nGuitar: Jonny Buckland\nPercussion: Luis Jardim\nMixer: Mark "Spike" Stent\nProducer, Programmer: Markus Dravs\nMixer: Matt Green\nDulcimer: Matt McGinn\nAssistant: Noah Goldstein\nMixer: Olga Fitzroy\nMixer: Pierre Eiras\nProducer: Rik Simpson\nEditor, Programmer: Robin Baynton\nDrums: Will Champion\nComposer: Brian Eno\nComposer: Chris Martin\nComposer: Guy Berryman\nComposer: Jonny Buckland\nComposer: Will Champion\n\nAuto-generated by YouTube.',
  },
  [[generateId()]]: {
    'favicon': 'https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png',
    'title': 'Coldplay & The Chainsmokers - Something Just Like This (Tokyo Remix) - YouTube',
    'description': 'Something Just Like This (Tokyo Remix) by Coldplay & The Chainsmokers filmed and recorded in Tokyo and all around the world.  \n\nStarring Isak H\nDirected by Mat Whitecross\nProduced by Hannah Clark\nEdited by Chris Roebuck\nAnimation by James Zwadlo\n\nDownload Something Just Like This (Tokyo Remix) - http://smarturl.it/itSJLTtokyo\n\nTaken from the upcoming Kaleidoscope EP. Order the EP now: https://parlopho.ne/KaleidoscopeEP. \n\nThe Chainsmokers debut album \'Memories... Do Not Open\' is out now!\nBuy & Stream: http://smarturl.it/TCSMemories\nPhysical CD: http://smarturl.it/TCSMemoriesCD\nVinyl LP: http://smarturl.it/TCSMemoriesVinyl\n\nFollow The Chainsmokers:\nhttp://www.youtube.com/thechainsmokers\nhttp://www.twitter.com/thechainsmokers\nhttp://www.facebook.com/thechainsmokers\nhttp://www.instagram.com/thechainsmokers\nhttp://www.soundcloud.com/thechainsmo...\n\nFollow Coldplay: \nhttp://coldplay.com/\nhttps://www.facebook.com/coldplay/\nhttps://twitter.com/coldplay\nhttps://www.instagram.com/coldplay',
    'url': 'https://www.youtube.com/watch?v=Pj-Q9vx0EeQ',
  },
  [[generateId()]]: {
    'url': 'https://www.youtube.com/watch?v=YykjpeuMNEk',
    'title': 'Coldplay - Hymn For The Weekend (Official Video) - YouTube',
    'favicon': 'https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png',
    'description': 'The second single to be taken from Coldplay\'s acclaimed new album, A Head Full Of Dreams (out now). Download the song from http://smarturl.it/AHFOD or stream at http://cldp.ly/cpspotify\n\nGet A Head Full Of Dreams now:\n– iTunes http://smarturl.it/AHFOD\n– Amazon http://smarturl.it/AHFODamazon\n– Google Play http://smarturl.it/AHFODgplay\n– TIDAL http://cldp.ly/AHFOD-tidal\n– CD http://smarturl.it/AHFODcd\n– Vinyl http://smarturl.it/AHFODvinyl\n\nCREDITS:\nProduction Company: Black Dog Films with River Studios\nDirector: Ben Mor \nExecutive Producers: Katie Dolan & Mike Rothenberg\nProducer: Nina Dluhy-Miller\nVFX supervisor (Los Angeles): Uzi Mor\nVFX supervisor (Tel Aviv): Yaron Yashinski\nVisual Effects by Yashinski Studio: Shay Wax, Elad Naim, Or Terry & Dan Geiger\nColdplay Manager: Dave Holmes (http://www.daveholmesmanagement.com)',
  },
  [[generateId()]]: {
    'url': 'https://www.youtube.com/watch?v=8W68jBXPSL4',
    'title': 'Major Minus - YouTube',
    'favicon': 'https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png',
    'description': 'Provided to YouTube by Warner Music Group\n\nMajor Minus · Coldplay\n\nMylo Xyloto\n\n℗ 2011 Parlophone Records Ltd, a Warner Music Group Company\n\nAssistant: Andy Rugg\nMastering  Engineer: Bob Ludwig\nMasterer: Bob Ludwig\nKeyboards, Vocals: Brian Eno\nVocals: Chris Martin\nAssistant: Christian Green\nProducer: Daniel Green\nMixer: Dave Emery\nBass: Guy Berryman\nAssistant: Ian Shea\nGuitar: Jonny Buckland\nTambourine: Luis Jardim\nMixer: Mark "Spike" Stent\nProducer, Programmer: Markus Dravs\nMixer: Matt Green\nGuitar: Matt McGinn\nMixer: Michael Brauer\nAssistant: Noah Goldstein\nMixer: Pierre Eiras\nProducer, Vocals: Rik Simpson\nEditor, Programmer: Robin Baynton\nMixer: Ryan Gilligan\nDrums: Will Champion\nComposer: Brian Eno\nComposer: Chris Martin\nComposer: Guy Berryman\nComposer: Jonny Buckland\nComposer: Will Champion\n\nAuto-generated by YouTube.',
  },
  [[generateId()]]: {
    'url': 'https://www.youtube.com/watch?v=7pfX1OKqP80',
    'title': 'Everglow - YouTube',
    'favicon': 'https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png',
    'description': 'Provided to YouTube by Warner Music Group\n\nEverglow · Coldplay\n\nA Head Full Of Dreams\n\n℗ 2015 Parlophone Records Limited, a Warner Music Group Company\n\nAdditional  Engineer: Bill Rahko\nMasterer: Chris Allgood\nAll  Instruments, Vocals: Chris Martin\nAdditional  Engineer: Daniel Green\nCo- Producer: Daniel Green\nMasterer: Emily Lazar\nAll  Instruments: Guy Berryman\nBacking  Vocals: Gwyneth Paltrow\nAdditional  Engineer: Jaime Sickora\nMixer: Jaime Sickora\nAll  Instruments: Jonny Buckland\nMixer: Matt Tuggle\nKeyboards, Programmer: Mikkel S Eriksen\nEngineer: Miles Walker\nMixer: Rik Simpson\nEngineer: Robin Baynton\nMixer: Robin Baynton\nMixer: Roxy Pope\nProducer: Stargate for 45th & 3rd Music LLC.\nMixer: Tom Bailey\nKeyboards, Programmer: Tor Eric Hermansen\nAll  Instruments, Vocals: Will Champion\nComposer: Chris Martin\nComposer: Guy Berryman\nComposer: Jonny Buckland\nComposer: Mikkel S Eriksen\nComposer: Tor Erik Hermansen\nComposer: Will Champion\n\nAuto-generated by YouTube.',
  },
  [[generateId()]]: {
    'url': 'https://www.youtube.com/watch?v=Oncu0bgdcXU',
    'title': 'Fix You - YouTube',
    'favicon': 'https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png',
    'description': 'Provided to YouTube by Warner Music Group\n\nFix You · Coldplay\n\nX & Y\n\n℗ 2005 Parlophone Records Ltd, a Warner Music Group Company\n\nProducer, Vocals: Coldplay\nProduced by: Coldplay\nGuitarra: Jon Buckland\nGuitarra: Chris Martin\nGuitar, Piano, Vocals: Chris Martin\nProgrammer: Coldplay\nProducer: Coldplay and Ken Nelson\nProduction: Danton Supple\nMasterer: George Marino\nBass: Guy Berryman\nGuitar: Jon Buckland\nEngineer, Mixer: Keith Gary\nProduced by: Ken Nelson\nProducer: Ken Nelson\nEngineer: Mark Phythian\nRecording  Engineer: Mark Phythian\nMastering  Engineer: George Marino\nRecorder: Mark Phythian\nMixer: Michael H. Brauer\nAssistant: Tim Roe\nAssistant: Rob Smith\nAssistant: John Withnal\nAssistant: Jake Jackson\nAssistant: Jon Bailey\nAssistant: Mat Lejeune\nAssistant: Mike Pierce\nDrums: Will Champion\nMixer: Will Hensley\nComposer: Chris Martin\nComposer: Guy Berryman\nComposer: Jonny Buckland\nComposer: Will Champion\n\nAuto-generated by YouTube.',
  },
  [[generateId()]]: {
    'url': 'https://www.youtube.com/watch?v=zOQ4ld6NsXE',
    'title': 'Viva La Vida - YouTube',
    'favicon': 'https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png',
    'description': 'Provided to YouTube by Warner Music Group\n\nFix You · Coldplay\n\nX & Y\n\n℗ 2005 Parlophone Records Ltd, a Warner Music Group Company\n\nProducer, Vocals: Coldplay\nProduced by: Coldplay\nGuitarra: Jon Buckland\nGuitarra: Chris Martin\nGuitar, Piano, Vocals: Chris Martin\nProgrammer: Coldplay\nProducer: Coldplay and Ken Nelson\nProduction: Danton Supple\nMasterer: George Marino\nBass: Guy Berryman\nGuitar: Jon Buckland\nEngineer, Mixer: Keith Gary\nProduced by: Ken Nelson\nProducer: Ken Nelson\nEngineer: Mark Phythian\nRecording  Engineer: Mark Phythian\nMastering  Engineer: George Marino\nRecorder: Mark Phythian\nMixer: Michael H. Brauer\nAssistant: Tim Roe\nAssistant: Rob Smith\nAssistant: John Withnal\nAssistant: Jake Jackson\nAssistant: Jon Bailey\nAssistant: Mat Lejeune\nAssistant: Mike Pierce\nDrums: Will Champion\nMixer: Will Hensley\nComposer: Chris Martin\nComposer: Guy Berryman\nComposer: Jonny Buckland\nComposer: Will Champion\n\nAuto-generated by YouTube.',
  },
  [[generateId()]]: {
    'url': 'https://www.youtube.com/watch?v=bOyqszY_rBc',
    'title': 'U.F.O. - YouTube',
    'favicon': 'https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png',
    'description': 'Provided to YouTube by Warner Music Group\n\nU.F.O. · Coldplay\n\nMylo Xyloto\n\n℗ 2011 Parlophone Records Ltd, a Warner Music Group Company\n\nAssistant: Andy Rugg\nMastering  Engineer: Bob Ludwig\nMasterer: Bob Ludwig\nVocals: Chris Martin\nAssistant: Christian Green\nProducer: Daniel Green\nMixer: Dave Emery\nStrings: Davide Rossi\nStrings: Davide Rossi\nBass: Guy Berryman\nGuitar: Jonny Buckland\nMixer: Mark "Spike" Stent\nProducer: Markus Dravs\nMixer: Matt Green\nMixer: Olga Fitzroy\nMixer: Pierre Eiras\nProducer: Rik Simpson\nEditor, Programmer: Robin Baynton\nDrums: Will Champion\nComposer: Brian Eno\nComposer: Chris Martin\nComposer: Guy Berryman\nComposer: Jonny Buckland\nComposer: Will Champion\n\nAuto-generated by YouTube.',
  },
  [[generateId()]]: {
    'url': 'https://www.youtube.com/watch?v=m7ibdhm4Xog',
    'title': 'Magic - YouTube',
    'favicon': 'https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png',
    'description': 'Provided to YouTube by Warner Music Group\n\nMagic · Coldplay\n\nMagic\n\n℗ 2014 Parlophone Records Limited, a Warner Music Group Company.\n\nAll  Instruments: Chris Martin\nAll  Instruments: Guy Berryman\nAll  Instruments: Jonny Buckland\nAll  Instruments: Will Champion\nAssistant: Adam Miller\nAssistant: Bill Rahko\nAssistant: Christian Green\nAssistant: Fiona Cruickshank\nAssistant: Jeff Gartenbaum\nAssistant: John Prestage\nAssistant: Joseph Hartwell\nAssistant: Joseph Hartwell Jones\nAssistant: Kyle Stevens\nAssistant: Matt McGinn\nAssistant: Neil Lambert\nAssistant: Nicolas Essig\nAssistant: Pablo Hernandez\nAssistant: Roxy Pope\nAssistant: Tom Bailey\nEngineer: Chris Owens\nEngineer: Jaime Sickora\nEngineer: Joe Visciano\nEngineer: Matt Wiggins\nEngineer: Olga Fitzroy\nMasterer: Ted Jensen\nMixer: Geoff Swan\nMixer: Mark \'Spike\' Stent\nProducer: Coldplay\nProducer, Programmer: Daniel Green\nProducer: Paul Epworth\nProducer: Rik Simpson\nProgrammer: Paul Epworth\nProgrammer: Rik Simpson\nVocals: Chris Martin\nVocals: Will Champion\nWriter: Chris Martin\nWriter: Guy Berryman\nWriter: Jonny Buckland\nWriter: Will Champion\n\nAuto-generated by YouTube.',
  },
  [[generateId()]]: {
    'url': 'https://www.youtube.com/watch?v=9qnqYL0eNNI',
    'title': 'Yellow - YouTube',
    'favicon': 'https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png',
    'description': 'Provided to YouTube by Warner Music Group\n\nYellow · Coldplay\n\nParachutes\n\n℗ 2000 Parlophone Records Ltd, a Warner Music Group Company\n\nAssistant  Engineer: Andrea Wright\nGuitar, Piano, Vocals: Chris Martin\nProduced by: Coldplay\nVocals: Coldplay\nProducer: Coldplay\nGuitarra: Guy Berryman\nGuitarra: Chris Martin\nMasterer: George Marino at Sterling Sound\nGuitar: Guy Berryman\nAssistant  Engineer: Jon Coles\nDrums: Jonny Buckland\nProduced by: Ken Nelson\nEngineer, Producer: Ken Nelson\nProduction: Mark Phythian\nMixer: Michael Brauer\nAssistant  Engineer: Paul Read\nAssistant  Engineer: Simon Barnicott\nGuitar, Guitarra: Will Champion\nWriter: Chris Martin\nWriter: Guy Berryman\nWriter: Jon Buckland\nWriter: Will Champion\n\nAuto-generated by YouTube.',
  },
  [[generateId()]]: {
    'url': 'https://www.youtube.com/watch?v=waKvorfmuB8',
    'title': 'Green Eyes - YouTube',
    'favicon': 'https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png',
    'description': 'Provided to YouTube by Warner Music Group\n\nGreen Eyes · Coldplay\n\nA Rush Of Blood To The Head\n\n℗ 2002 Parlophone Records Ltd, a Warner Music Group Company\n\nEngineer: Andrea Wright\nStrings: Ann Lines\nStrings: Audrey Riley\nEngineer: Ben Thackeray\nProduced by: Coldplay\nStrings: Coldplay\nVocals: Coldplay\nGuitarra: Chris Martin\nGuitar, Piano, Vocals: Chris Martin\nStrings: Chris Tombling\nMixer, Producer: Coldplay\nGuitar: Guy Berryman\nEngineer: Jon Bailey\nStrings: Richard George\nStrings: Susan Dench\nGuitarra: Will Champion\nGuitarra: Guy Berryman\nEngineer: Jon Withnal\nDrums: Jonny Buckland\nProduced by: Ken Nelson\nRecording  Engineer: Ken Nelson\nEngineer, Mixer, Producer, Recorder: Ken Nelson\nStrings: Laura Melhewish\nStrings: Leo Payne\nEngineer: Mark Phythian\nRecording  Engineer: Mark Phythian\nMixer, Production, Recorder: Mark Phythian\nStrings: Peter Lale\nEngineer: Rik Simpson\nGuitar: Will Champion\nArranger: Audrey Riley\nComposer: Berryman\nComposer: Buckland\nComposer: Champion\nArranger: Coldplay\nComposer: Guy Berryman\nComposer: Jonny Buckland\nComposer: Martin\nComposer: Will Champion\n\nAuto-generated by YouTube.',
  },
  [[generateId()]]: {
    'url': 'https://www.youtube.com/watch?v=0aN61rAve-8',
    'title': 'Up in Flames - YouTube',
    'favicon': 'https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png',
    'description': 'Provided to YouTube by Warner Music Group\n\nUp in Flames · Coldplay\n\nMylo Xyloto\n\n℗ 2011 Parlophone Records Ltd, a Warner Music Group Company\n\nAssistant: Andy Rugg\nMastering  Engineer: Bob Ludwig\nMasterer: Bob Ludwig\nVocals: Chris Martin\nAssistant: Christian Green\nMixer, Producer: Daniel Green\nMixer: Dave Emery\nBass: Guy Berryman\nGuitar: Jonny Buckland\nMixer: Mark "Spike" Stent\nProducer: Markus Dravs\nMixer: Matt Green\nMixer: Pierre Eiras\nMixer, Producer, Vocals: Rik Simpson\nEditor, Programmer: Robin Baynton\nDrums: Will Champion\nComposer: Chris Martin\nComposer: Guy Berryman\nComposer: Jonny Buckland\nComposer: Will Champion\n\nAuto-generated by YouTube.',
  },
  [[generateId()]]: {
    'url': 'https://www.youtube.com/watch?v=KnLNG0WnGsI',
    'title': 'Coldplay - All I Can Think About Is You (Official Lyric Video) - YouTube',
    'favicon': 'https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png',
    'description': 'Taken from the Kaleidoscope EP. Order the EP now: https://parlopho.ne/KaleidoscopeEP. \n\nFollow Coldplay: \nhttp://coldplay.com/\nhttps://www.facebook.com/coldplay/\nhttps://twitter.com/coldplay\nhttps://www.instagram.com/coldplay\n\nCredits:\nDirector/ Animation: I Saw John First\nAnimation: Matt Lloyd\nProducer: Zoe Muslim\nProduction Company: Strange Beast',
  },
  [[generateId()]]: {
    'url': 'https://www.youtube.com/watch?v=WXmTEyq5nXc',
    'title': 'Coldplay - Hypnotised (Official Lyric Video) - YouTube',
    'favicon': 'https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png',
    'description': 'Taken from the Kaleidoscope EP. Order the EP now: https://parlopho.ne/KaleidoscopeEP. \n\nFollow Coldplay: \nhttp://coldplay.com/\nhttps://www.facebook.com/coldplay/\nhttps://twitter.com/coldplay\nhttps://www.instagram.com/coldplay\n \nDirected by Mary Wigmore\nProduced by Casey Byron\nExecutive Produced by Arts & Sciences\nArt Direction by Andy Goldman\nCinematography by Peter Zuccarini\nEdited by Sean Lagrange',
  },
  [[generateId()]]: {
    'url': 'https://www.youtube.com/watch?v=we-LaiQNY5s',
    'title': 'Coldplay - A L I E N S (Official Lyric Video) - YouTube',
    'favicon': 'https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png',
    'description': 'Taken from the Kaleidoscope EP. Order the EP now: https://parlopho.ne/KaleidoscopeEP. All song proceeds to MOAS\'s work rescuing migrants in peril at sea - https://www.moas.eu/\n\nFollow Coldplay: \nhttp://coldplay.com/\nhttps://www.facebook.com/coldplay/\nhttps://twitter.com/coldplay\nhttps://www.instagram.com/coldplay\n\nDirector: Ben Jones\nCreative Director: Diane Martel\nProducer: Jamie Miller\nAnimation: Bento Box Entertainment',
  },
  [[generateId()]]: {
    'url': 'https://www.youtube.com/watch?v=Gqxf2tbJopM',
    'title': 'Cemeteries of London - YouTube',
    'favicon': 'https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png',
    'description': 'Provided to YouTube by Warner Music Group\n\nCemeteries of London · Coldplay\n\nViva La Vida - Prospekt\'s March Edition\n\n℗ 2008 Parlophone Records Ltd, a Warner Music Group Company\n\nTechnician: Andy Rugg\nEngineer &  Mixer: Andy Wallace\nMasterer: Bob Ludwig\nHand  Clap, Producer: Brian Eno\nBass: Guy Berryman\nEngineer &  Mixer: John O\'Mahoney\nGuitarra: Jon Buckland\nGuitarra: Chris Martin\nProduced by: Brian Eno\nTechnician: Brian Thorne\nGuitar, Piano, Vocals: Chris Martin\nProduced by: Markus Dravs\nProduced by: Rik Simpson\nMixer: Andy Wallace\nTechnician: Daniel Green\nTechnician: Dom Mokes\nProgrammer: Francois Chevallier\nEngineer: John O\'Mahoney\nEngineer: Jan Petrov\nMastering  Engineer: Bob Ludwig\nEngineer &  Mixer: Jan Petrov\nGuitar: Jon Buckland\nProducer: Markus Dravs\nTechnician: Olga Fitzroy\nProducer: Rik Simpson\nDrums: Will Champion\nComposer: Chris Martin\nComposer: Guy Berryman\nComposer: Jonny Buckland\nComposer: Will Champion\n\nAuto-generated by YouTube.',
  },
  [[generateId()]]: {
    'url': 'https://www.youtube.com/watch?v=te4GczYtgEM',
    'title': '42 - YouTube',
    'favicon': 'https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png',
    'description': 'Provided to YouTube by Warner Music Group\n\n42 · Coldplay\n\nViva La Vida - Prospekt\'s March Edition\n\n℗ 2008 Parlophone Records Ltd, a Warner Music Group Company\n\nGuitarra: Jon Buckland\nGuitarra: Chris Martin\nProduced by: Brian Eno\nMixer: Rik Simpson\nProduced by: Rik Simpson\nEngineer: Andy Rugg\nEngineer &  Mixer, Technician: Andy Rugg\nBacking  Vocals: Andy Rugg\nMasterer: Bob Ludwig\nProducer: Brian Eno\nBacking  Vocals: Brian Eno\nGuitar, Piano, Vocals: Chris Martin\nTechnician: Daniel Green\nStrings: Davide Rossi\nBass: Guy Berryman\nGuitar: Jon Buckland\nProducer: Markus Dravs\nGuitarra: Matt McGinn\nProduced by: Markus Dravs\nGuitar: Matt McGinn\nMixer: Michael Brauer\nHand  Clap: Phil Harvey\nEngineer &  Mixer, Producer, Vocals: Rik Simpson\nBacking  Vocals: Stuart Peck\nBacking  Vocals: Tim Crompton\nDrums: Will Champion\nEngineer: Will Hensley\nMastering  Engineer: Bob Ludwig\nEngineer &  Mixer: Michael Brauer\nEngineer &  Mixer: Will Hensley\nComposer: Chris Martin\nComposer: Guy Berryman\nComposer: Jonny Buckland\nComposer: Will Champion\n\nAuto-generated by YouTube.',
  },
  [[generateId()]]: {
    'url': 'https://www.facebook.com/profile.php?id=100001654370875',
    'favicon': 'http://graph.facebook.com/100001654370875/picture?type=square',
    'title': 'Varisa Gumpangkum',
    'description': 'Varisa Gumpangkum is on Facebook. Join Facebook to connect with Varisa Gumpangkum and others you may know. ',
  },
  [[generateId()]]: {
    'url': 'https://www.facebook.com/profile.php?id=100005336778940',
    'title': 'Somil Jain',
    'favicon': 'http://graph.facebook.com/100005336778940/picture?type=square',
    'description': 'Somil Jain is on Facebook. Join Facebook to connect with Somil Jain and others you may know. ',
  },
  [[generateId()]]: {
    'url': 'https://www.facebook.com/search/top/',
    'title': 'fuad youssef - Facebook Search',
    'favicon': 'https://static.xx.fbcdn.net/rsrc.php/yo/r/iRmz9lCMBD2.ico',
    'description': 'We couldn\'t find anything for .kihlijh\nLooking for people or posts? Try entering a name, location, or different words.',
  },
  [[generateId()]]: {
    'url': 'https://www.facebook.com/profile.php?id=100009215512559',
    'title': 'Jae Sohn',
    'favicon': 'http://graph.facebook.com/100009215512559/picture?type=square',
    'description': 'Jae Sohn is on Facebook. Join Facebook to connect with Jae Sohn and others you may know. ',
  },
  [[generateId()]]: {
    'url': 'https://www.facebook.com/profile.php?id=100005405416775',
    'title': 'Kong Weng Hei',
    'favicon': 'http://graph.facebook.com/100005405416775/picture?type=square',
    'description': 'Kong Weng Hei is on Facebook. Join Facebook to connect with Kong Weng Hei and others you may know. ',
  },
  [[generateId()]]: {
    'url': 'https://www.facebook.com/profile.php?id=100009705393730',
    'title': 'Hannah Kim',
    'favicon': 'http://graph.facebook.com/100009705393730/picture?type=square',
    'description': 'Hannah Kim is on Facebook. Join Facebook to connect with Hannah Kim and others you may know. ',
  },
};
const ranksMap = {};
for (const id1 of Object.keys(webData)) {
  ranksMap[id1] = [];
  for (const id2 of Object.keys(webData)) {
    if (id1 === id2) continue;
    const web1 = webData[id1];
    const web2 = webData[id2];
    const sameDomain = isSameDomain(web1.url, web2.url);
    ranksMap[id1].push({
      web: id2,
      count: 1 + (sameDomain ? Math.random() * 15 : Math.random() * 2) | 0,
      duration: 10000 + (sameDomain ? Math.random() * 1000 * 60 * 60 : Math.random() * 1000 * 60 * 10) | 0,
    });
  }
}

const tabUrls = {};
const tabTimestamps = {};
chrome.tabs.onUpdated.addListener(function (tabId, changeInfo, tab) {
  if ('favIconUrl' in changeInfo) {
    const id = getId(tab.url);
    if (!webData[id]) webData[id] = {};
    webData[id].favicon = changeInfo.favIconUrl;
  }
  if ('title' in changeInfo) {
    const id = getId(tab.url);
    if (!webData[id]) webData[id] = {};
    webData[id].title = changeInfo.title;
  }
  if ('url' in changeInfo) {
    const now = Number(new Date());
    const fromUrl = tabUrls[tabId];
    const toUrl = changeInfo.url;
    const fromId = Object.keys(webData).find(key => webData[key] === fromUrl);
    const toId = Object.keys(webData).find(key => webData[key] === toUrl);
    const duration = tabId in tabTimestamps ? now - tabTimestamps[tabId] : 0;

    setTimeout(() =>
      chrome.tabs.executeScript(tab.id, { code: ~toUrl.indexOf('youtube') ? 'document.getElementsByClassName(\'content\')[0].textContent;' : 'getMeta(\'description\');' }, description => {
        if (!webData[toId]) webData[toId] = {};
        webData[toId].description = Array.isArray(description) ? description[0] : description;
      }), 1000);


    if (fromUrl) {
      if (!ranksMap[fromId]) ranksMap[fromId] = [];
      const rank = ranksMap[fromId].find(rank => rank.web === toId);
      if (rank) {
        rank.count++;
        rank.duration += duration;
      } else {
        webData[toId] = {
          url: toUrl,
          title: tab.title,
          favicon: tab.favIconUrl,
          description: '',
          ...(webData[toId] || {}),
        };
        ranksMap[fromId].push({
          web: toId,
          count: 1,
          duration,
        });
      }
    }

    tabUrls[tabId] = toUrl;
    tabTimestamps[tabId] = now;
  }
});

chrome.extension.onMessage.addListener((url, sender, sendResponse) => {
  const id = getId(url);
  if (!ranksMap[id]) ranksMap[id] = [];
  const ranks = ranksMap[id];
  while (ranks.length < 3) {
    const webId =
      shuffle(Object.keys(webData).filter(id => webData[id].url && isSameDomain(url, webData[id].url))).find(id => ranks.every(rank => rank.web !== id)) ||
      shuffle(Object.keys(webData)).find(id => ranks.every(rank => rank.web !== id));
    ranks.push({
      web: webId,
      count: (Math.random() * 2 | 0) + 1,
      duration: (Math.random() * 1000 * 60 * 8 | 0) + 1000,
    });
  }
  sendResponse(ranks.sort((r1, r2) => r2.count - r1.count).map(rank => ({ ...rank, web: webData[rank.web] })));
});
